FROM python:3.10-slim
WORKDIR /app
COPY BGC_Explorer/bgc_explorer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY BGC_Explorer/bgc_explorer /app
ENV BGC_EXPLORER_PORT=8080
CMD python3 server.py --port $BGC_EXPLORER_PORT
