name: MALDIquant

channels:
  - conda-forge
  - bioconda

dependencies:
  - r-base=3.6
  - r-maldiquant
  - r-maldiquantforeign
  - r-yaml
  - ijson
  - pandas
  - tqdm
  - joblib
  - json5
  - pip
  - pip:
    - psims
    - pyteomics