channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas
  - openpyxl
  - pip:
    - massql
    - requests
    - python-dotenv
    - PyYAML
    - pymzml
    - pyteomics
    - plotly
    - scikit-learn
    - psims